name: Test Donut Falls myloasm assembly

on: [pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          
      - name: Run Donut Falls
        run: |
          docker --version
          
          nextflow run . -profile docker,test \
            -c .github/workflows/github_actions.config \
            --assembler myloasm

          tree donut_falls

      - name: Check files
        run: |
          ls  donut_falls/multiqc/multiqc_report.html
          #ls  donut_falls/df/myloasm/assembly_primary.fa donut_falls/df/myloasm/final_contig_graph.gfa
          cat donut_falls/summary/donut_falls_summary.json